apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: {{.Annotation}}
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: macos
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: {{.Name}}
    kubernetes.io/os: macos
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
    env: test
  name: {{.Name}}
spec:
  taints: # Avoid scheduling actual running pods to fake Node
    - effect: NoSchedule
      key: kwok.x-k8s.io/node
      value: fake
status:
  allocatable:
    cpu: 32
    memory: 256Gi
    pods: 110
  capacity:
    cpu: 32
    memory: 256Gi
    pods: 110
  nodeInfo:
    architecture: amd64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running