apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-scheduler-0
  namespace: kube-system
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 100
  serviceName: scheduler-0
  selector:
    matchLabels:
      component: kube-scheduler
      tier: control-plane
      node: master-0
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: kube-scheduler
        tier: control-plane
        node: master-0
        control: test-master
      name: kube-scheduler
      namespace: kube-system
    spec:
      containers:
      - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        - --bind-address=<MASTER-NODE-0-IP>
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
        - --kube-api-qps=200   # default: 50
        - --kube-api-burst=400   # default: 100
        image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.27.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: <MASTER-NODE-0-IP>
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 15
        name: kube-scheduler
        resources:
          requests:
            cpu: 100m
            memory: 260M
        startupProbe:
          failureThreshold: 24
          httpGet:
            host: <MASTER-NODE-0-IP>
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 15
        volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      nodeName: test-master-0
      priority: 2000001000
      priorityClassName: system-node-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - hostPath:
          path: /etc/kubernetes/scheduler.conf
          type: FileOrCreate
        name: kubeconfig

