apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.6.1
  name: node-exporter
  namespace: monitoring
# full metrics
# spec:
#   endpoints:
#   - interval: 15s
#     port: metrics
#     relabelings:
#     - action: replace
#       sourceLabels:
#       - __metrics_path__
#       targetLabel: metrics_path
#     scheme: http
#   jobLabel: node-exporter
#   namespaceSelector:
#     matchNames:
#     - monitoring
#   selector:
#     matchLabels:
#       app.kubernetes.io/component: exporter
#       app.kubernetes.io/name: node-exporter
#       app.kubernetes.io/part-of: kube-prometheus
# filtered metrics
spec:
  endpoints:
  - interval: 15s
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: node-exporter
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: kube-prometheus

