apiVersion: v1
kind: Service
metadata:
  name: test-master
  namespace: monitoring
  labels:
    app.kubernetes.io/name: test-master
    k8s-app: test-master
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP

