apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: updater-requests
spec:
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: exempt
  rules:
    - resourceRules:
        - apiGroups: ['', 'flowcontrol.apiserver.k8s.io']
          clusterScope: true
          namespaces: ['*']
          resources: ['pods', 'flowschemas', 'prioritylevelconfigurations']
          verbs: ['*']
      subjects:
        - kind: ServiceAccount
          serviceAccount:
            name: updater
            namespace: default
