apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: empty
spec:
  matchingPrecedence: 1100
  priorityLevelConfiguration:
    name: empty
  rules:
    - resourceRules:
        - apiGroups: ['*']
          clusterScope: true
          namespaces: ['*']
          resources: ['*']
          verbs: ['*']
      subjects:
        - kind: ServiceAccount
          serviceAccount:
            name: merkury-empty
            namespace: default

